version: '3.8'
services:
  audit-api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    networks:
      - audit-network
networks:
  audit-network:
    driver: bridge