# Mini-Linux mit Python 3.9
FROM python:3.9-slim

WORKDIR /app

# Kopiere requirements.txt
COPY requirements.txt .

# Installiere alle Pakete aus requirements.txt
RUN pip install -r requirements.txt

# Kopiere main.py von deinem Computer in den Container
COPY main.py .

# Port 8000 öffnen"
EXPOSE 8000

# Wenn Container startet: Starte FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]