# Mini-Linux mit Python
FROM python:3.9-slim

# MLflow installieren
RUN pip install mlflow

# Port für MLflow Server
EXPOSE 5000

# MLflow Server starten
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]